### ISSUE TITLE
i have a probleme

### ISSUE THREAD

**Issue by hakanonymos** [tedirghazali/alga-js#1]
can you help me i have this probleme with npm

sudo npm install alga-js

Password:
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "alga-js" under a package
npm ERR! also called "alga-js". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookair/.npm/_logs/2021-03-21T03_29_48_115Z-debug.log

**Comment by tedirghazali** [comment]
sorri, I'm late to response this, I'll check that problem

**Comment by tedirghazali** [comment]
this issue already closed by hakanonymos, so I already see what is the problem, but you can try install using tarball or git instead like npm install github:tedirghazali/alga-js or using yarn or maybe you can download the file first
