### ISSUE TITLE
$array.show() no longer working

### ISSUE THREAD

**Issue by Utitofon-Udoekong** [tedirghazali/alga-js#4]
The latest update seems to have removed array.show(). Would like to know what is the replacement for this function. Below is my usage example
![Screenshot_18](https://user-images.githubusercontent.com/69417647/161856547-93c22095-d249-468a-a444-fd0e2421d98a.png)

Error I'm getting is this
![Screenshot_1](https://user-images.githubusercontent.com/69417647/161856677-5e1a71fb-f1aa-4844-a0e3-2179c140eac3.png)

**Comment by tedirghazali** [comment]
the replacement is pageInfo, you can see it in my github js folder in
paginateArray. js

Pada tanggal Rab, 6 Apr 2022 04.59, utitofon ***@***.***>
menulis:

**Comment by Utitofon-Udoekong** [comment]
Thank you works fine
