### ISSUE TITLE
Alga.js export not found on netlify

### ISSUE THREAD

**Issue by Utitofon-Udoekong** [tedirghazali/alga-js#6]
I am having an issue when deploying to netlify.

![Screenshot_28](https://user-images.githubusercontent.com/69417647/169873886-13af05ff-d5f1-4495-9371-e6d26acb84ab.png)

![Screenshot_30](https://user-images.githubusercontent.com/69417647/169875465-d502c1b2-eb51-4a72-9e83-04543e2961bb.png)

I think it has to do with an import from the package. This is how I use it.

![Screenshot_29](https://user-images.githubusercontent.com/69417647/169874160-9fc5090d-6727-43e0-8359-611a77b7a8de.png)

**Comment by tedirghazali** [comment]
oh, yes, I have change some structure of library, now you can use "import { paginate } from 'alga-js/array'"

**Comment by Utitofon-Udoekong** [comment]
This is what I get. I am using the wood-5 version

![Screenshot_25](https://user-images.githubusercontent.com/69417647/170108463-00ca63b2-a29d-4fb5-9fc0-f1e4adcae8af.png)

**Comment by tedirghazali** [comment]
oh okay, I have merged
